import { ar } from "../../types";
import type { ProjectInput } from "../../schema";
import appStore from "./images/app-store.png";
import assessment from "./images/assessment.png";
import certificate from "./images/certificate.png";
import internship from "./images/internship.png";
import interviewAr from "./images/interview-ar.png";
import interviewEn from "./images/interview-en.png";
import landingAr from "./images/landing-ar.png";
import landingEn from "./images/landing-en.png";
import playStore from "./images/play-store.png";

/**
 * Sources: Portfolio-assets/the-intern/documents/ROLE-NOTES.md (the operator's
 * own account, five decision stories), STATUS.md for capture caveats, and the
 * verified screenshots in the same pack.
 *
 * Published copy deliberately excludes every internal identifier the notes
 * carry — key IDs, keystore names, commit hashes, private symbol names and
 * file paths. Those stay in ROLE-NOTES.
 *
 * No invented metrics. Only the measured facts appear: the 6-of-8 versus
 * 0-of-8 worker reproduction, the (N−1)/N failure rate, retry budgets, and the
 * published build numbers. No download or user counts.
 *
 * EN/AR only. French is deferred and is never claimed.
 */
export const theIntern: ProjectInput = {
  slug: "the-intern",
  title: "The Intern",
  positioning: "AI-powered internship simulation, on web, iOS and Android",
  summary:
    "A platform where students run a simulated internship: an AI interview, generated daily tasks, an assessment and a certificate — delivered across web and both app stores, in English and Arabic.",
  category: { en: "AI product", ar: ar("منتج ذكاء اصطناعي") },
  year: "2026",
  duration: "April 2026 – present",
  status: "production",
  role: "Full-stack Engineer — sole engineer on the product",
  platforms: ["web", "ios", "android"],
  languages: ["en", "ar"],
  stack: [
    "react",
    "vite",
    "typescript",
    "tailwind",
    "fastapi",
    "postgres",
    "capacitor",
    "i18next",
    "stripe",
    "gitlabCi",
  ],
  links: {
    live: "https://theintern.app",
  },
  confidentiality: "limited",
  depth: "case-study",
  featured: true,
  order: 4,
  updatedAt: "2026-09-19",

  cover: {
    src: landingEn,
    alt: "The Intern landing page showing the headline about launching a career through AI-powered internship simulations",
    treatment: "browser",
    url: "theintern.app",
    dir: "ltr",
    locale: "en",
  },

  seo: {
    title: "The Intern — AI internship simulation on web, iOS and Android",
    description:
      "Sole engineer on an AI internship platform: model fallback, multi-worker auth, Android signing-key recovery, and an Arabic RTL port across web and mobile.",
  },

  sections: [
    {
      type: "overview",
      body: [
        "The Intern is a product of elama.ai: instead of listing vacancies, it puts a student through a simulated internship. They pick a company and a role, sit an interview run by a language model, work through generated daily tasks, get assessed, and finish with a certificate.",
        "It runs as a web app and as native apps on both stores, sharing one backend. The interesting engineering is not the screens — it is everything that has to hold up when the product depends on a model that can fail, sessions that must survive more than one server process, and two app stores that reject builds for reasons that only appear after upload.",
      ],
    },
    {
      type: "role",
      title: "My role",
      ownership: {
        owned: [
          "Full-stack engineering across web, iOS and Android",
          "AI integration reliability: model fallback, retries and response handling",
          "Authentication under multi-worker deployment",
          "Android release, including recovering a lost signing key",
          "iOS build, signing and App Store Connect delivery",
          "The English/Arabic RTL port across both web and mobile",
        ],
        team: "Sole engineer on the product, working to the CEO's product direction at elama.ai.",
      },
      body: [
        "Six months as the only engineer on the product. Product direction was the CEO's; the engineering decisions below were mine.",
      ],
    },
    {
      type: "challenge",
      title: "A product whose content is generated, on platforms that reject you late",
      body: [
        "Everything a student sees in the middle of the journey — interview questions, task briefs, evaluations — is generated by an external model. That makes the model a hard dependency in the middle of a user's session: if it fails, the student gets a blank screen halfway through their internship.",
        "The second problem was subtler. The backend runs multiple worker processes, and authentication state was being held in the memory of whichever process happened to answer. Sign-ins failed intermittently, which is the worst kind of failure: it looks like bad luck rather than a bug.",
        "The third was delivery. Shipping to the App Store and Google Play from a Windows team means most mistakes do not surface as build errors — they surface as a rejection after upload, days later.",
      ],
    },
    {
      type: "approach",
      title: "Treating reliability as a product feature",
      body: [
        "The organising idea across all of this was that the student should never be exposed to an infrastructure problem. A dead model, a flaky network, a malformed response and a rejected build are all engineering concerns — none of them are the student's.",
        "That framing decided how failures were categorised, where state was kept, and how the Arabic port was staged so it could not break the English product on the way.",
      ],
    },
    {
      type: "solution",
      title: "The student journey",
      body: [
        "Choose a role, sit the interview, work the simulation, receive an assessment, leave with a certificate. Each step is generated for the role the student picked rather than pulled from a fixed bank.",
      ],
      figure: {
        src: internship,
        alt: "Internship overview on a phone showing the simulation's day plan and task progress",
        treatment: "phone",
        dir: "ltr",
        locale: "en",
      },
    },
    {
      type: "features",
      title: "The journey, end to end",
      items: [
        {
          title: "AI interview",
          body: "A generated interview for the chosen role, with open-ended questions and progress through the set.",
          figure: {
            src: interviewEn,
            alt: "AI interview screen on a phone showing question one of five with an answer box",
            treatment: "phone",
            dir: "ltr",
            locale: "en",
          },
        },
        {
          title: "Assessment",
          body: "A report built from the student's responses and behavioural results, downloadable as a PDF.",
          figure: {
            src: assessment,
            alt: "Onboarding assessment report on a phone showing a personality profile and skills portfolio",
            treatment: "phone",
            dir: "ltr",
            locale: "en",
          },
        },
        {
          title: "Certificate",
          body: "A completion certificate at the end of the simulation, with the result the student can share.",
          figure: {
            src: certificate,
            alt: "Completion certificate on a phone confirming the internship simulation was finished",
            treatment: "phone",
            dir: "ltr",
            locale: "en",
          },
        },
      ],
    },
    {
      type: "decisions",
      title: "Engineering decisions",
      stories: [
        {
          title: "Three kinds of AI failure, treated as three different problems",
          tags: ["ai-reliability", "ux"],
          problem: [
            "Interview questions, task briefs and evaluations all come from an external model. Any failure lands in the middle of a student's session as an empty screen.",
          ],
          rootCause: [
            "Three genuinely different failures were being handled identically: a model that has been retired and will never answer, a transient network problem that would succeed on a retry, and a response that arrives successfully but cannot be parsed.",
          ],
          decision: [
            "Separate them, and give each the response it actually deserves — skip, retry, or tolerate — with a strict rule that transport never judges content.",
          ],
          implementation: [
            "Requests run through a chain of models. A model reported as unavailable is skipped immediately rather than retried, because retrying something retired only burns time. Transient failures get a bounded retry budget — three attempts on the primary model, two on each alternate — so the worst-case wait stays predictable. Rejected keys rotate.",
            "The strict rule: any successful response is passed through untouched. Judging output quality belongs to a higher layer, not to the code responsible for fetching it. A tolerant parser absorbs formatting differences between models, and the fields that must belong to a fixed set are coerced back into it.",
          ],
          result: [
            "A single model failing became invisible to the student. The coercion step also closed a subtle leak: an unexpected category from a model used to surface as an English label inside the Arabic interface. Where only one model is configured, the original error is still raised unchanged, so existing behaviour did not shift.",
          ],
        },
        {
          title: "Proving the multi-worker bug before fixing it",
          tags: ["security", "data-integrity"],
          problem: [
            "Sign-in through LinkedIn failed intermittently with an invalid-state error, and the same fault later appeared in the Apple sign-in path. Intermittent auth failures are easy to dismiss as network noise.",
          ],
          rootCause: [
            "The authentication state was stored in a dictionary held in one process's memory. The request was written by one worker and the callback arrived at another, which had never seen it. With N workers, roughly (N−1)/N attempts fail — half at two workers, three quarters at four.",
          ],
          decision: [
            "Prove it experimentally before changing anything, then move the state somewhere every worker can see.",
          ],
          implementation: [
            "A reproduction script held everything constant — same code, same machine — and varied only the number of workers. At two workers, six of eight attempts failed. At one worker, none of eight did. Causes that fail deterministically with a different error were excluded first, so the result could only be explained by the worker count.",
            "The state then moved to a shared store with a short expiry and single-use consumption, and the same treatment was applied to the Apple one-time-code path. The Google path was already correct, so the fix was visible as a single missing line by comparison.",
          ],
          result: [
            "The intermittent failures stopped — and they stopped before the iOS build went to App Store review. That build declared Sign in with Apple as a feature, so a reviewer hitting the (N−1)/N failure rate would most likely have rejected it. A third case of the same family was found and logged rather than quietly left.",
          ],
        },
        {
          title: "Recovering a lost Android signing key",
          tags: ["deployment", "security"],
          problem: [
            "The original upload key for the published Android app was lost. Normally that is terminal: without it you cannot ship another update to an app that is already live.",
          ],
          rootCause: [
            "The key existed only where it had been generated, with nothing guarding against its loss and no process for how signing material was stored.",
          ],
          decision: [
            "Use the one recovery path that exists, then remove the conditions that made the loss possible.",
          ],
          implementation: [
            "Because Play App Signing was enabled, Google holds the final signing key and allows the upload key to be reset. A new upload keystore was generated, registered through that reset, and a signed bundle was published.",
            "Then the hardening: the release signing configuration reads its path, password and alias from environment variables or untracked properties rather than anything committed; keystore file types are ignored at the repository root and in the Android project; and with no credentials supplied the build produces an unsigned artifact rather than silently falling back.",
          ],
          result: [
            "The app is published on Google Play again despite the original key being gone, signed builds are reproducible on any machine or CI runner by passing the variables, and the replacement key is kept out of version control by construction.",
          ],
        },
        {
          title: "Shipping iOS from a Windows team",
          tags: ["deployment"],
          problem: [
            "An iOS release needs a Mac, certificates and provisioning. The team is on Windows, and anything missing shows up as a rejection after upload rather than as a build error.",
          ],
          rootCause: [
            "Moving the build to a cloud service that installs dependencies cleanly from the branch exposed differences between what worked locally and what a fresh environment would accept.",
          ],
          decision: [
            "Make the cloud build the source of truth and fix each difference there, rather than keeping a local machine that happens to work.",
          ],
          implementation: [
            "The dependency install was fixed at the configuration level so a clean install succeeds. Uploads moved to an App Store Connect API key instead of manual submission, with the distribution certificate and provisioning profile bound to the bundle identifier.",
            "When a build was rejected, the cause was diagnosed as a build-number collision rather than a signing fault, and the version and build numbers were raised together across both platforms so they could not drift apart again.",
          ],
          result: [
            "Both platforms now release from one branch with no local Mac. Version 1.0.7 is live on the App Store, and build 11 — version 1.0.8 — is uploaded and awaiting review. One risk is documented rather than closed: the native sync step needs to be mandatory in the pipeline, because the uploaded build carried fewer native plugins than the manifest declared.",
          ],
        },
        {
          title: "An Arabic port that could not be allowed to break English",
          tags: ["rtl", "ux"],
          problem: [
            "Two complete applications — web and mobile — had to work right-to-left in Arabic without disturbing the English product or the prompts the AI layer depends on.",
          ],
          rootCause: [
            "Right-to-left is not translation. Layout carries physical assumptions — margin-left, text-left, border-left — that have to become logical ones. And one class of error appears in no key-coverage test at all: values that come from the backend as fixed codes get printed raw when no display mapping exists for them.",
          ],
          decision: [
            "Stage the port in four phases instead of one large conversion, and fix hard rules about what may not change.",
          ],
          implementation: [
            "The rules: English output stays byte-for-byte identical, including plurals; Arabic uses Modern Standard Arabic with a locked glossary for the recurring product terms; and icon names, placeholder tokens and the English prompt structures the parser depends on are never touched. Fixed backend codes got a display mapping at the interface layer with a raw fallback.",
            "Verification ran in two layers: a headless pass resolving every key against the real objects, then a browser pass at desktop and phone widths confirming nothing overflowed in right-to-left. The global layout override that had been masking direction problems was removed last, once the pages beneath it were converted.",
          ],
          result: [
            "The port landed on both platforms with the shared files verified identical, and it is the change carried by the build now in review. The remaining issues are written down rather than quietly left: direction is only applied when the language is switched rather than on a fresh load, translated strings are captured when a screen first mounts, and some temporary overrides stay until the remaining pages are converted.",
          ],
        },
      ],
    },
    {
      type: "mirror",
      title: "The same product, both directions",
      body: [
        "English and Arabic of the same page. The Arabic here is genuine Arabic, not English inside a mirrored frame.",
      ],
      ltr: {
        src: landingEn,
        alt: "The Intern landing page in English, left to right",
        treatment: "browser",
        url: "theintern.app",
        dir: "ltr",
        locale: "en",
      },
      rtl: {
        src: landingAr,
        alt: "The Intern landing page in Arabic, mirrored right to left with translated headings and calls to action",
        treatment: "browser",
        url: "theintern.app",
        dir: "rtl",
        locale: "ar",
      },
      notes: [
        "Layout direction comes from the language, so one component tree serves both rather than a forked Arabic build.",
        "The full Arabic and right-to-left port across the app is the change carried by build 11 (1.0.8), uploaded and awaiting store review — so the currently published build shows Arabic coverage in progress rather than complete.",
      ],
    },
    {
      type: "rtlNote",
      title: "Where Arabic is genuine, and where it is not yet",
      body: [
        "Being precise about this matters more than claiming completeness. The interview flow and the app's navigation are genuinely Arabic — translated content, mirrored layout, Arabic controls. Parts of the generated reporting still render English text inside a right-to-left frame in the published build.",
        "That gap is exactly what the staged port addressed, and the build carrying it is with the stores now. Screenshots here are from what is published today, not from what is in review.",
      ],
      figure: {
        src: interviewAr,
        alt: "AI interview screen in Arabic on a phone, with the question, answer box and navigation buttons mirrored right to left",
        treatment: "phone",
        dir: "rtl",
        locale: "ar",
        caption:
          "The interview in Arabic: translated content and mirrored controls.",
      },
    },
    {
      type: "delivery",
      title: "Published on both stores",
      body: [
        "The product is live: version 1.0.7 on the App Store and on Google Play, with build 11 — version 1.0.8, carrying the Arabic port — uploaded and awaiting review.",
        "Both platforms release from a single branch through a cloud build, which is what makes shipping iOS possible without a Mac in the team at all.",
      ],
      figure: {
        src: appStore,
        alt: "The Intern listing on the App Store showing the app icon, publisher and screenshots",
        treatment: "plate",
        dir: "ltr",
        locale: "en",
      },
    },
    {
      type: "quality",
      title: "What was measured",
      body: [
        "These are the figures that were actually measured during the work. There are no user or download numbers here, because none were measured by me.",
      ],
      metrics: [
        {
          label: "Sign-in failures at two workers",
          before: "6 of 8",
          after: "0 of 8",
          method:
            "Reproduction script holding code and machine constant, varying only the worker count — two workers versus one",
          verification: "measured-local",
        },
        {
          label: "Expected failure rate under N workers",
          after: "(N−1)/N",
          method:
            "Derived from in-process state: 50% at two workers, 75% at four",
          verification: "observed",
        },
        {
          label: "Retry budget per request",
          after: "3 primary · 2 per alternate",
          method: "Bounded so worst-case response time stays predictable",
          verification: "observed",
        },
        {
          label: "Published versions",
          after: "1.0.7 live · build 11 (1.0.8) in review",
          method: "App Store and Google Play listings at time of writing",
          verification: "observed",
        },
      ],
    },
    {
      type: "outcome",
      title: "Outcome",
      body: [
        "A generated-content product that keeps working when the model does not, sign-ins that survive the number of workers the backend happens to run, an Android app still publishable after its signing key was lost, and an iOS release pipeline that needs no Mac.",
        "The Arabic port is staged and verified rather than bolted on, and what is not finished is written down instead of implied.",
      ],
      figure: {
        src: playStore,
        alt: "The Intern listing on Google Play showing the app, its category and screenshots",
        treatment: "plate",
        dir: "ltr",
        locale: "en",
      },
    },
    {
      type: "lessons",
      title: "What I would carry forward",
      body: [
        "Proving the multi-worker bug with a script that varied one thing was worth more than the fix itself. It turned an intermittent failure that could be argued about into a number, and it made the fix reviewable.",
        "The signing key taught the more uncomfortable lesson: a recovery path existing is luck, not process. The hardening that followed is what makes it a non-event next time.",
        "And splitting the Arabic port into phases, with English held byte-for-byte identical, is what let a two-platform port land without a regression in the language most of the product was already shipping in.",
      ],
    },
  ],
};
